version: '3.8'
services:
  docker_db:
    build: 
      context: ./Docker-files/db
    image: ayushman7/docker_db
    container_name: docker_dbdb
    ports:
      - "3306:3306"
    volumes:
    - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=amt@123

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
    

  vrpmq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  docker_app:  
    build: 
      context: ./Docker-files/app
    image: ayushman7/docker_app
    container_name: docker_app
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  docker_web:
    build: 
      context: ./Docker-files/web
    image: ayushman7/docker_web
    container_name: docker_web
    ports:
      - "80:80"
    
volumes:
  vprodbdata: {}
  vproappdata: {}